observable_instruments = [
    {'o_id': 1, 'zerodha_instrument_token': 256265, 'zerodha_exchange_token': 1001,
     'zerodha_trading_symbol': 'NIFTY 50', 'zerodha_name': 'NIFTY 50', 'zerodha_expiry': None,
     'zerodha_lot_size': 0, 'zerodha_instrument_type': 'EQ', 'zerodha_segment': 'INDICES',
     'zerodha_exchange': 'NSE', 'angel_token': 99926000, 'angel_symbol': 'Nifty 50', 'angel_name': 'NIFTY',
     'angel_expiry': None, 'angel_lot_size': 1, 'angel_instrument_type': 'AMXIDX',
     'angel_exchange_segment': 'NSE', 'angel_trading_symbol': 'Nifty 50', 'shoonya_exchange': 'NSE',
     'shoonya_token': 26000, 'shoonya_lot_size': 1, 'shoonya_name': 'Nifty 50',
     'shoonya_trading_symbol': 'NIFTY INDEX', 'shoonya_expiry': None, 'shoonya_instrument_type': 'INDEX',
     'shoonya_option_type': None, 'alice_exchange': 'NSE', 'alice_exchange_segment': 'nse_idx',
     'alice_expiry_date': None, 'alice_formatted_ins_name': 'NIFTY 50', 'alice_instrument_type': 'INDEX',
     'alice_lot_size': None, 'alice_option_type': 'XX', 'alice_pdc': None, 'alice_strike_price': None,
     'alice_symbol': 'NIFTY 50', 'alice_token': '26000', 'alice_trading_symbol': 'NIFTY',
     'search_key': 'NIFTY'},
    {'o_id': 2, 'zerodha_instrument_token': 260105, 'zerodha_exchange_token': 1016,
     'zerodha_trading_symbol': 'NIFTY BANK', 'zerodha_name': 'NIFTY BANK',
     'zerodha_expiry': None, 'zerodha_lot_size': 0, 'zerodha_instrument_type': 'EQ',
     'zerodha_segment': 'INDICES', 'zerodha_exchange': 'NSE',
     'angel_token': 99926009, 'angel_symbol': 'Nifty Bank',
     'angel_name': 'BANKNIFTY', 'angel_expiry': None, 'angel_lot_size': 1,
     'angel_instrument_type': 'AMXIDX', 'angel_exchange_segment': 'NSE',
     'angel_trading_symbol': 'Nifty Bank', 'shoonya_exchange': 'NSE',
     'shoonya_token': 26009, 'shoonya_lot_size': 1, 'shoonya_name': 'Nifty Bank',
     'shoonya_trading_symbol': 'NIFTY BANK', 'shoonya_expiry': None,
     'shoonya_instrument_type': 'INDEX', 'shoonya_option_type': None,
     'alice_exchange': 'NSE', 'alice_exchange_segment': 'nse_idx',
     'alice_expiry_date': None, 'alice_formatted_ins_name': 'NIFTY BANK',
     'alice_instrument_type': 'INDEX', 'alice_lot_size': None,
     'alice_option_type': 'XX', 'alice_pdc': None, 'alice_strike_price': None,
     'alice_symbol': 'NIFTY BANK', 'alice_token': '26009',
     'alice_trading_symbol': 'BANKNIFTY', 'search_key': 'BANKNIFTY'},

    {'o_id': 4, 'zerodha_instrument_token': 288009, 'zerodha_exchange_token': 1125,
     'zerodha_trading_symbol': 'NIFTY MID SELECT', 'zerodha_name': 'NIFTY MIDCAP SELECT (MIDCPNIFTY)',
     'zerodha_expiry': None, 'zerodha_lot_size': 0, 'zerodha_instrument_type': 'EQ',
     'zerodha_segment': 'INDICES', 'zerodha_exchange': 'NSE', 'angel_token': 99926074,
     'angel_symbol': 'NIFTY MID SELECT', 'angel_name': 'MIDCPNIFTY', 'angel_expiry': None,
     'angel_lot_size': 1, 'angel_instrument_type': 'AMXIDX', 'angel_exchange_segment': 'NSE',
     'angel_trading_symbol': 'NIFTY MID SELECT', 'shoonya_exchange': 'NSE', 'shoonya_token': 26074,
     'shoonya_lot_size': 1, 'shoonya_name': 'NIFTY MID SELECT', 'shoonya_trading_symbol': 'MIDCPNIFTY',
     'shoonya_expiry': None, 'shoonya_instrument_type': 'INDEX', 'shoonya_option_type': None,
     'alice_exchange': 'NSE', 'alice_exchange_segment': 'nse_idx', 'alice_expiry_date': None,
     'alice_formatted_ins_name': 'NIFTY MIDCAP SELECT', 'alice_instrument_type': 'INDEX',
     'alice_lot_size': None, 'alice_option_type': 'XX', 'alice_pdc': None, 'alice_strike_price': None,
     'alice_symbol': 'NIFTY MIDCAP SELECT', 'alice_token': '26074', 'alice_trading_symbol': 'MIDCPNIFTY',
     'search_key': 'MIDCPNIFTY'},
    {'o_id': 5, 'zerodha_instrument_token': 257801, 'zerodha_exchange_token': 1007,
     'zerodha_trading_symbol': 'NIFTY FIN SERVICE', 'zerodha_name': 'NIFTY FIN SERVICE',
     'zerodha_expiry': None, 'zerodha_lot_size': 0, 'zerodha_instrument_type': 'EQ',
     'zerodha_segment': 'INDICES', 'zerodha_exchange': 'NSE', 'angel_token': 99926037,
     'angel_symbol': 'Nifty Fin Service', 'angel_name': 'FINNIFTY', 'angel_expiry': None,
     'angel_lot_size': 1, 'angel_instrument_type': 'AMXIDX',
     'angel_exchange_segment': 'NSE', 'angel_trading_symbol': 'Nifty Fin Service',
     'shoonya_exchange': 'NSE', 'shoonya_token': 26037, 'shoonya_lot_size': 1,
     'shoonya_name': 'Nifty Fin Services', 'shoonya_trading_symbol': 'FINNIFTY',
     'shoonya_expiry': None, 'shoonya_instrument_type': 'INDEX',
     'shoonya_option_type': None, 'alice_exchange': 'NSE',
     'alice_exchange_segment': 'nse_idx', 'alice_expiry_date': None,
     'alice_formatted_ins_name': 'NIFTY FIN SERVICE', 'alice_instrument_type': 'INDEX',
     'alice_lot_size': None, 'alice_option_type': 'XX', 'alice_pdc': None,
     'alice_strike_price': None, 'alice_symbol': 'NIFTY FIN SERVICE',
     'alice_token': '26037', 'alice_trading_symbol': 'FINNIFTY', 'search_key': 'FINNIFTY'}]
